{% set name = "dclab" %}
{% set version = "0.50.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dclab-{{ version }}.tar.gz
  sha256: 9f2bacb656b74067b9761654e742683ff837c1ed3af6e8103e1a17031b242ec2

build:
  skip: true  # [py<39 or win]
  entry_points:
    - dclab-compress = dclab.cli:compress
    - dclab-condense = dclab.cli:condense
    - dclab-join = dclab.cli:join
    - dclab-repack = dclab.cli:repack
    - dclab-split = dclab.cli:split
    - dclab-tdms2rtdc = dclab.cli:tdms2rtdc
    - dclab-verify-dataset = dclab.cli:verify_dataset
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy >=1.21
    - pip
    - python
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - fcswrite >=0.5.0
    - h5py >=3.0.0
    - hdf5plugin >=3.3.1
    - imageio
    - nptdms >=0.23.0
    - {{ pin_compatible('numpy') }}
    - python
    - requests
    - rpy2 >=2.9.4
    - scipy >=1.8.0
    - tensorflow >=2.0

test:
  imports:
    - dclab
  commands:
    - pip list
    - pip check
    - dclab-compress --help
    - dclab-condense --help
    - dclab-join --help
    - dclab-repack --help
    - dclab-split --help
    - dclab-tdms2rtdc --help
    - dclab-verify-dataset --help
  requires:
    - pip

about:
  home: https://github.com/ZELLMECHANIK-DRESDEN/dclab
  summary: Library for real-time deformability cytometry (RT-DC)
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
